# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8489d31b31c93ede75d4394de470e68095f904d4330543a93c3c3a67d31f7b092f011a721469ae8413d7195932db3058dce8d29fc77e31ca1c0479224046544

test:
  secret_key_base: 0e417cd65009648d3c66b608282a264b94b1b2946e1b673fbccf7c7c4b9208c2e7056accac1889cd7d2840dd54b16276b496e954e56755158a7aa1c5bc64b954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
